---
    apiVersion: v1
    kind: Service
    metadata:
      name: fortune-app
      namespace: example-fortune
      labels:
        app: fortune-service
    spec:
      ports:
      - port: 80
        targetPort: 8080
        name: web
      type: NodePort
      selector:
        app: fortune-app