---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: fortune-app
    namespace: example-fortune
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: fortune-app
    strategy:
      type: RollingUpdate
      rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
    template:
      metadata:
        name: fortune-app
        annotations:
          prometheus.io/path: "/actuator/prometheus"
          prometheus.io/port: "8080"
          prometheus.io/scrape: "true"
        labels:
          app: fortune-app
      spec:
        containers:
        - image: 10.149.88.33:30002/library/example-fortune:d5616b9
          name: fortune-app
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
          - name: SPRING_REDIS_HOST
            value: "redis.redis-ns.svc.cluster.local"
          readinessProbe:
            httpGet:
              path: /all-fortunes.html
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 30
