---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: git-assets
- name: current-app-info
- name: version

outputs:
- name: app-manifest-output

run:
  path: git-assets/ci/tasks/app-manifest-prep
