platform: linux


image_resource:
  type: docker-image
  source:
    repository: azwickey/deploy-worker
    tag: "latest"
inputs:
- name: git-assets
outputs:
- name: releases
run:
  path: git-assets/ci/tasks/package-spinn.sh
