groups:
- name: main
  jobs:
  - unit-tests
  - build-artifact
  - ship

resource_types:
- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: git-assets
  type: git
  source:
    branch: master
    uri: git@github.com:azwickey-pivotal/fortune-demo.git
    private_key: {{github-key}}
resources:
  - name: release
    type: gcs-resource
    source:
      bucket: spinnaker-az
      json_key: {{google-json-key}}
      regexp: fortune-demo/fortune-demo.jar
jobs:
- name: unit-tests
  serial: true
  public: true
  plan:
  - get: git-assets
    trigger: true
  - task: mvn-test
    file: git-assets/ci/tasks/unit-tests.yml
- name: build-artifact
  serial: true
  public: true
  plan:
  - get: git-assets
    trigger: true
    passed:
    - unit-tests
  - task: mvn-package
    file: git-assets/ci/tasks/mvn-package-spinn.yml
    params:
      CF_APP: {{cf-app-name}}
- name: ship
  serial: true
  public: true
  plan:
  - get: git-assets
    trigger: true
    passed:
    - build-artifact
  - put: release
    params: { file: ../releases/fortune-demo.jar }
